default: dispplugin$(DSOEXT)

dispplugin$(DSOEXT): dispplugin.o compute_custom_disp.o
	$(LD) -o $@ $^

.cpp.o:
	$(CXX) -o $@ $(CXXFLAGS) -c $<

compute_custom_disp.o: compute_custom_disp.cpp compute_custom_disp.h
dispplugin.o: dispplugin.cpp compute_custom_disp.h

clean:
	rm -rf *~ *.so *.dylib *.o log.lammps CMakeCache.txt CMakeFiles
